project:
  type: website

website:
  title: "Deepsha Menghani"
  
  favicon: "images/linkedinpic.jpg"
  
  page-footer:
    center: |
      <span class="container"><strong>[Contact Deepsha Menghani](mailto:menghani.deepsha@gmail.com)</strong></span>
    left: |
      <span class="container"><strong>Made with [Posit Quarto](https://quarto.org/)</strong></span>
    background: "#004E4F"
    
  navbar:
    
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: tidytuesday.qmd
        text: TidyTuesday
      - href: resume.qmd
        text: Resume
      - href: waresume.qmd
        text: Wednesday Addam's resume
        
    right:
      - icon: mastodon
        href: https://fosstodon.org/@deepsha
        aria-label: Quarto Mastodon
      - icon: twitter
        href: https://twitter.com/bigdatadipper
        aria-label: Quarto Twitter
      - icon: linkedin
        href: https://linkedin.com/in/deepshamenghani
        aria-label: Quarto LinkedIn
      - icon: github
        href: https://github.com/deepshamenghani/
        aria-label: Quarto Github
        
  search: 
    location: navbar
    type: overlay

format:
  html:
    theme:
      light: [cosmo, theme_light_custom.scss]
      dark: [cosmo, theme_dark_custom.scss]
    css: styles.css
    citations-hover: true
    code-link: true
    code-fold: show
    code-tools: false
    code-block-border-left: "#004E4F"
    

    
editor: visual

